### ISSUE TITLE
When the repo is transferred, the current `volta data` is not syncing

### ISSUE THREAD

**Issue by phojie** [volta-net/feedback#81]

**Comment by phojie** [comment]
nvm

**Comment by smarroufin** [comment]
Hi @phojie

Actually you could be right, you probably encountered the deletion of your repository on Volta (does not affect it on GitHub 😌).
This behaviour is not intentional, neither intended. It is due to the fact the repository moves to another owner and loses its associated Volta GitHub application. It turns out that Volta sees it as an uninstall, so it deletes the repository on our servers.

To avoid it in the future, you might want to install the Volta GitHub application on "all repositories" of your destination owner.
![CleanShot 2023-08-22 at 11.15.08@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2023_08_22_at_11_15_08_2x_2613e2af97.png)

Thanks for the feedback anyways 🙂
